### get puestos
GET http://localhost:3001/api/puestos

###
POST http://localhost:3001/api/puestos
Content-Type: application/json

{
  "nombre": "Gerente"
}

### Get employee by id
GET http://localhost:3001/api/puestos/1

### Update an employee
PUT http://localhost:3001/api/puestos/1
Content-Type: application/json

{
  "nombre": "Gerente actualizado"
}

### Delete an employee
DELETE http://localhost:3001/api/puestos/1

### PING
GET http://localhost:3001/ping